language: php
php:
  - '7.0'
  - '7.1'
before_script:
 - wget https://github.com/alanxz/rabbitmq-c/archive/v0.8.0.tar.gz
 - tar xzpf v0.8.0.tar.gz
 - cd rabbitmq-c-0.8.0/ && autoreconf -i && ./configure && make && sudo make install && cd - && sudo ldconfig
 - pecl install amqp
 - pecl install msgpack
 - pecl install swoole
 - phpenv config-add travis-php-ext.ini
 - composer install -o --ignore-platform-reqs
