language: php
php:
  - '7.0'
  - '7.1'
before_script:
 - apt-get install -y librabbitmq-dev
 - pecl install amqp
 - pecl install msgpack
 - pecl install swoole
 - phpenv config-add travis-php-ext.ini
 - composer install -o --ignore-platform-reqs
