language: php
php:
  - '7.0'
  - '7.1'
before_script:
 - wget https://github.com/rabbitmq/rabbitmq-c/archive/librabbitmq-0.1-amqp_0_8.tar.gz
 - tar xzpf librabbitmq-0.1-amqp_0_8.tar.gz
 - cd rabbitmq-c-librabbitmq-0.1-amqp_0_8/ && autoreconf -i && ./configure && make && make install && ldconfig && cd -
 - pecl install amqp
 - pecl install msgpack
 - pecl install swoole
 - phpenv config-add travis-php-ext.ini
 - composer install -o --ignore-platform-reqs
